/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumCourseCategory } from "./EnumCourseCategory";
import {
  IsEnum,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { EnrollmentUpdateManyWithoutCoursesInput } from "./EnrollmentUpdateManyWithoutCoursesInput";
import { Type } from "class-transformer";
import { ResourceUpdateManyWithoutCoursesInput } from "./ResourceUpdateManyWithoutCoursesInput";
import { SessionUpdateManyWithoutCoursesInput } from "./SessionUpdateManyWithoutCoursesInput";

@InputType()
class CourseUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumCourseCategory,
  })
  @IsEnum(EnumCourseCategory)
  @IsOptional()
  @Field(() => EnumCourseCategory, {
    nullable: true,
  })
  category?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => EnrollmentUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => EnrollmentUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => EnrollmentUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  enrollments?: EnrollmentUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => ResourceUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => ResourceUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => ResourceUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  resources?: ResourceUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => SessionUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => SessionUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => SessionUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  sessions?: SessionUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { CourseUpdateInput as CourseUpdateInput };
