/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumCourseCategory } from "./EnumCourseCategory";
import {
  IsEnum,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { EnrollmentCreateNestedManyWithoutCoursesInput } from "./EnrollmentCreateNestedManyWithoutCoursesInput";
import { Type } from "class-transformer";
import { ResourceCreateNestedManyWithoutCoursesInput } from "./ResourceCreateNestedManyWithoutCoursesInput";
import { SessionCreateNestedManyWithoutCoursesInput } from "./SessionCreateNestedManyWithoutCoursesInput";

@InputType()
class CourseCreateInput {
  @ApiProperty({
    required: false,
    enum: EnumCourseCategory,
  })
  @IsEnum(EnumCourseCategory)
  @IsOptional()
  @Field(() => EnumCourseCategory, {
    nullable: true,
  })
  category?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => EnrollmentCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => EnrollmentCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => EnrollmentCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  enrollments?: EnrollmentCreateNestedManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => ResourceCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => ResourceCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => ResourceCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  resources?: ResourceCreateNestedManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => SessionCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => SessionCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => SessionCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  sessions?: SessionCreateNestedManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { CourseCreateInput as CourseCreateInput };
